Testing build-chunked

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -111,28 +111,28 @@ jobs:
   #      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
   #    - name: Build
   #      run: ./ci/clang-build-check.sh
-  integration:
-    name: "Container Integration"
-    needs: [build, build-tests]
-    runs-on: ubuntu-latest
-    container: quay.io/fedora/fedora-coreos:testing-devel
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Download build
-        uses: actions/download-artifact@v4.1.7
-        with:
-          name: install.tar
-      - name: Install
-        run: tar -C / -xzvf install.tar && rm -f install.tar
-      - name: Download tests
-        uses: actions/download-artifact@v4.1.7
-        with:
-          name: tests.tar
-      - name: Install Tests
-        run: tar -C / -xzvf tests.tar && rm -f tests.tar
-      - name: Integration tests
-        run: ./ci/test-container.sh
+  # integration:
+  #   name: "Container Integration"
+  #   needs: [build, build-tests]
+  #   runs-on: ubuntu-latest
+  #   container: quay.io/fedora/fedora-coreos:testing-devel
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Download build
+  #       uses: actions/download-artifact@v4.1.7
+  #       with:
+  #         name: install.tar
+  #     - name: Install
+  #       run: tar -C / -xzvf install.tar && rm -f install.tar
+  #     - name: Download tests
+  #       uses: actions/download-artifact@v4.1.7
+  #       with:
+  #         name: tests.tar
+  #     - name: Install Tests
+  #       run: tar -C / -xzvf tests.tar && rm -f tests.tar
+  #     - name: Integration tests
+  #       run: ./ci/test-container.sh
   # Try to keep this in sync with https://github.com/ostreedev/ostree-rs-ext/blob/1fc115a760eeada22599e0f57026f58b22efded4/.github/workflows/rust.yml#L163
   container-build:
     name: "Container build"
@@ -160,95 +160,95 @@ jobs:
       with:
         log-level: warn
         command: check bans sources licenses
-  compose:
-    name: "Compose tests"
-    needs: build
-    runs-on: ubuntu-latest
-    container:
-      image: registry.ci.openshift.org/coreos/coreos-assembler:latest
-      options: "--user root --privileged -v /var/tmp:/var/tmp"
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Install test dependencies
-        run: ./ci/install-test-deps.sh
-      - name: Download build
-        uses: actions/download-artifact@v4.1.7
-        with:
-          name: install.tar
-      - name: Install
-        run: tar -C / -xzvf install.tar
-      - name: Integration tests
-        run: env TMPDIR=/var/tmp JOBS=3 ./tests/compose.sh
-  compose-image:
-    name: "compose-image tests"
-    needs: build
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        RELEASE: ['40', '41', '42']
-    container:
-      image: registry.ci.openshift.org/coreos/coreos-assembler:latest
-      options: "--user root --privileged -v /var/tmp:/var/tmp"
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Install test dependencies
-        run: ./ci/install-test-deps.sh
-      - name: Download build
-        uses: actions/download-artifact@v4.1.7
-        with:
-          name: install.tar
-      - name: Install
-        run: tar -C / -xzvf install.tar
-      - name: Integration tests
-        run: env TMPDIR=/var/tmp JOBS=3 RELEASE=${RELEASE} ./tests/compose-image.sh
-        env:
-          RELEASE: ${{ matrix.RELEASE }}
-  compose-rootfs:
-    name: "compose-rootfs tests"
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      # https://github.com/containers/podman/discussions/17362
-      - name: Get a newer podman for heredoc support (from debian testing)
-        run: |
-          set -eux
-          echo 'deb [trusted=yes] https://ftp.debian.org/debian/ testing main' | sudo tee /etc/apt/sources.list.d/testing.list
-          sudo apt update
-          sudo apt install -y crun/testing podman/testing skopeo/testing
-          # Something is confused in latest GHA here
-          sudo rm /var/lib/containers -rf
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Download build
-        uses: actions/download-artifact@v4.1.7
-        with:
-          name: install.tar
-      - name: Test compose-rootfs
-        run: |
-          cd tests/compose-rootfs
-          tar -xzvf ../../install.tar
-          sudo podman build -v $(pwd)/usr/bin/rpm-ostree:/run/build/rpm-ostree:ro --security-opt=label=disable --cap-add=all --device /dev/fuse -t localhost/test -f Containerfile .
-  container-encapsulate:
-    name: "Encapsulate tests"
-    needs: build
-    runs-on: ubuntu-latest
-    container:
-      image: registry.ci.openshift.org/coreos/coreos-assembler:latest
-      options: "--user root --privileged -v /var/tmp:/var/tmp"
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Download build
-        uses: actions/download-artifact@v4.1.7
-        with:
-          name: install.tar
-      - name: Install
-        run: tar -C / -xzvf install.tar
-      - name: Integration tests
-        run: env TMPDIR=/var/tmp ./tests/encapsulate.sh
+  # compose:
+  #   name: "Compose tests"
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: registry.ci.openshift.org/coreos/coreos-assembler:latest
+  #     options: "--user root --privileged -v /var/tmp:/var/tmp"
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Install test dependencies
+  #       run: ./ci/install-test-deps.sh
+  #     - name: Download build
+  #       uses: actions/download-artifact@v4.1.7
+  #       with:
+  #         name: install.tar
+  #     - name: Install
+  #       run: tar -C / -xzvf install.tar
+  #     - name: Integration tests
+  #       run: env TMPDIR=/var/tmp JOBS=3 ./tests/compose.sh
+  # compose-image:
+  #   name: "compose-image tests"
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       RELEASE: ['40', '41', '42']
+  #   container:
+  #     image: registry.ci.openshift.org/coreos/coreos-assembler:latest
+  #     options: "--user root --privileged -v /var/tmp:/var/tmp"
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Install test dependencies
+  #       run: ./ci/install-test-deps.sh
+  #     - name: Download build
+  #       uses: actions/download-artifact@v4.1.7
+  #       with:
+  #         name: install.tar
+  #     - name: Install
+  #       run: tar -C / -xzvf install.tar
+  #     - name: Integration tests
+  #       run: env TMPDIR=/var/tmp JOBS=3 RELEASE=${RELEASE} ./tests/compose-image.sh
+  #       env:
+  #         RELEASE: ${{ matrix.RELEASE }}
+  # compose-rootfs:
+  #   name: "compose-rootfs tests"
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # https://github.com/containers/podman/discussions/17362
+  #     - name: Get a newer podman for heredoc support (from debian testing)
+  #       run: |
+  #         set -eux
+  #         echo 'deb [trusted=yes] https://ftp.debian.org/debian/ testing main' | sudo tee /etc/apt/sources.list.d/testing.list
+  #         sudo apt update
+  #         sudo apt install -y crun/testing podman/testing skopeo/testing
+  #         # Something is confused in latest GHA here
+  #         sudo rm /var/lib/containers -rf
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Download build
+  #       uses: actions/download-artifact@v4.1.7
+  #       with:
+  #         name: install.tar
+  #     - name: Test compose-rootfs
+  #       run: |
+  #         cd tests/compose-rootfs
+  #         tar -xzvf ../../install.tar
+  #         sudo podman build -v $(pwd)/usr/bin/rpm-ostree:/run/build/rpm-ostree:ro --security-opt=label=disable --cap-add=all --device /dev/fuse -t localhost/test -f Containerfile .
+  # container-encapsulate:
+  #   name: "Encapsulate tests"
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: registry.ci.openshift.org/coreos/coreos-assembler:latest
+  #     options: "--user root --privileged -v /var/tmp:/var/tmp"
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Download build
+  #       uses: actions/download-artifact@v4.1.7
+  #       with:
+  #         name: install.tar
+  #     - name: Install
+  #       run: tar -C / -xzvf install.tar
+  #     - name: Integration tests
+  #       run: env TMPDIR=/var/tmp ./tests/encapsulate.sh
   test-build-chunked-oci:
     name: "build-chunked-oci tests"
     needs: build-c9s
@@ -313,21 +313,21 @@ jobs:
         with:
           name: install-c9s.tar
           path: install.tar
-  # Doc: https://github.com/redhat-plumbers-in-action/differential-shellcheck#usage
-  differential-shellcheck:
-    name: Differential ShellCheck
-    runs-on: ubuntu-latest
-
-    permissions:
-      security-events: write
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Differential ShellCheck
-        uses: redhat-plumbers-in-action/differential-shellcheck@v4
-        with:
-          severity: warning
-          token: ${{ secrets.GITHUB_TOKEN }}
+  # # Doc: https://github.com/redhat-plumbers-in-action/differential-shellcheck#usage
+  # differential-shellcheck:
+  #   name: Differential ShellCheck
+  #   runs-on: ubuntu-latest
+  #
+  #   permissions:
+  #     security-events: write
+  #
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Differential ShellCheck
+  #       uses: redhat-plumbers-in-action/differential-shellcheck@v4
+  #       with:
+  #         severity: warning
+  #         token: ${{ secrets.GITHUB_TOKEN }}
